### ISSUE TITLE
Text being made white but background not changing

### ISSUE THREAD

**Issue by clubby789** [useignition/DarkMode#3]
This has occurred on Snapchat and Reddit so far. The backgrounds remain white, but the tweak changes the text to white, making it unreadable.

**Comment by useignition** [comment]
We will look into this!

**Comment by clubby789** [comment]
I tried hooking SCCheetahFeedComponentView (the class that holds each person in your snapchat contacts, which inherits from UIView.) On layoutSubviews, I set its background colour to black. However, this worked intermittently, with colours flickering between black and white as I scrolled or touched the cell.

**Comment by useignition** [comment]
We already have a fix for that. We have already published it.

**Comment by clubby789** [comment]
Not sure if this should be closed just yet, as the cells are still white for a moment before turning black when they are rendered.
